export type JobPositionDataProps = {
  id:number,
  company:string,
  logo:string,
  new:boolean,
  featured:boolean,
  position:string,
  role:string,
  level:string,
  postedAt:string,
  contract:string,
  location:string,
  languages:string[],
  tools:string[]
}
export type JobPositionProps = {
  id:number,
  company:string,
  logo:string,
  new:boolean,
  featured:boolean,
  position:string,
  role:string,
  level:string,
  postedAt:string,
  contract:string,
  location:string,
  languages:string[],
  tools:string[],
  handleAddFilter:Function
}